In [14]:
import pandas as pd
pd.options.display.float_format = '{:.4f}'.format

In [44]:
df_res = pd.read_csv('res.csv')
df_res[df_res['Modelo'] == 'No Lineal']

,Nombre,Modelo,bias_gow,bias_cop,rmse_gow,rmse_cop,pearson_gow,pearson_cop,si_gow,si_cop
32,Bilbao-Vizcaya,No Lineal,-0.1201,-0.1475,0.3569,0.3642,0.9590,0.9580,0.1851,0.1889
33,Cabo_de_Pennas,No Lineal,-0.1318,-0.1437,0.3942,0.3686,0.9441,0.9517,0.1946,0.1819
34,Estaca_de_Bares,No Lineal,-0.1319,-0.1741,0.3884,0.4170,0.9604,0.9552,0.1570,0.1685
35,Villano-Sisargas,No Lineal,-0.1320,-0.1395,0.4044,0.3944,0.9534,0.9559,0.1601,0.1561
36,Cabo_Silleiro,No Lineal,-0.1251,-0.1141,0.3726,0.3421,0.9616,0.9675,0.1553,0.1426
37,Golfo_de_Cadiz,No Lineal,-0.0491,-0.1236,0.2648,0.3952,0.9235,0.8467,0.2176,0.3247
38,Alboran,No Lineal,-0.0709,-0.1679,0.2945,0.4047,0.8573,0.7826,0.4318,0.5934
39,Cabo_de_Gata,No Lineal,-0.1056,-0.1602,0.3201,0.3851,0.9124,0.8816,0.3135,0.3772
40,Cabo_de_Palos,No Lineal,-0.0805,-0.1111,0.2761,0.3118,0.9160,0.8987,0.2705,0.3054
41,Valencia,No Lineal,-0.0900,-0.1092,0.3368,0.3465,0.8250,0.8232,0.4088,0.4205
42,Tarragona,No Lineal,-0.0627,-0.0960,0.2649,0.3301,0.9096,0.8673,0.2985,0.3720
43,Cabo_Begur,No Lineal,-0.1474,-0.2225,0.3917,0.4647,0.9338,0.9113,0.2988,0.3544
44,Dragonera,No Lineal,-0.1229,-0.1881,0.3404,0.4132,0.9212,0.8915,0.3172,0.3851
45,Mahon,No Lineal,-0.1007,-0.1822,0.3178,0.4096,0.9509,0.9232,0.2444,0.3150
46,Gran_Canaria,No Lineal,-0.0634,-0.0600,0.2600,0.2492,0.9207,0.9268,0.1549,0.1484
47,Tenerife,No Lineal,-0.0917,-0.0892,0.2977,0.2944,0.7738,0.7766,0.3401,0.3363

In [45]:
for column in df_res:
    if column != 'Nombre' and column != 'Modelo':
        print(f"{column}: {df_res[df_res['Modelo'] == 'No Lineal'][column].mean():.4f}")

bias_gow: -0.1016
bias_cop: -0.1393
rmse_gow: 0.3301
rmse_cop: 0.3682
pearson_gow: 0.9139
pearson_cop: 0.8949
si_gow: 0.2592
si_cop: 0.2982