In [14]:
import pandas as pd
pd.options.display.float_format = '{:.4f}'.format

In [57]:
df_res = pd.read_csv('res.csv')
df_res[df_res['Modelo'] == '3DVar']

,Nombre,Modelo,bias_gow,bias_cop,rmse_gow,rmse_cop,pearson_gow,pearson_cop,si_gow,si_cop
48,Bilbao-Vizcaya,3DVar,0.0941,0.2645,0.1185,0.2394,0.9959,0.9911,0.0615,0.1242
49,Cabo_de_Pennas,3DVar,0.2744,0.0650,0.2536,0.1280,0.9887,0.9949,0.1252,0.0632
50,Estaca_de_Bares,3DVar,0.0342,0.1517,0.1274,0.2214,0.9957,0.9894,0.0515,0.0895
51,Villano-Sisargas,3DVar,0.0039,0.1275,0.2048,0.2089,0.9881,0.9895,0.0811,0.0827
52,Cabo_Silleiro,3DVar,0.0292,0.1346,0.1231,0.1345,0.9956,0.9968,0.0513,0.0561
53,Golfo_de_Cadiz,3DVar,0.0105,0.0920,0.1363,0.2287,0.9803,0.9649,0.1120,0.1879
54,Alboran,3DVar,-0.0038,0.1315,0.0988,0.2366,0.9812,0.9667,0.1449,0.3468
55,Cabo_de_Gata,3DVar,0.1157,0.2722,0.1655,0.3189,0.9824,0.9844,0.1621,0.3124
56,Cabo_de_Palos,3DVar,0.0417,0.1684,0.1333,0.2650,0.9802,0.9825,0.1305,0.2596
57,Valencia,3DVar,0.0817,0.1963,0.1516,0.3131,0.9892,0.9807,0.1840,0.3800
58,Tarragona,3DVar,0.0675,0.1946,0.1522,0.2981,0.9804,0.9801,0.1716,0.3359
59,Cabo_Begur,3DVar,0.2478,0.5521,0.2293,0.4309,0.9873,0.9888,0.1749,0.3286
60,Dragonera,3DVar,0.1132,0.2924,0.1374,0.3242,0.9935,0.9830,0.1281,0.3021
61,Mahon,3DVar,0.0972,0.3593,0.1131,0.3270,0.9953,0.9872,0.0870,0.2514
62,Gran_Canaria,3DVar,0.0144,0.0827,0.1223,0.1658,0.9801,0.9847,0.0729,0.0988
63,Tenerife,3DVar,0.0502,0.0322,0.1451,0.1169,0.9611,0.9560,0.1657,0.1336

In [58]:
for column in df_res:
    if column != 'Nombre' and column != 'Modelo':
        print(f"{column}: {df_res[df_res['Modelo'] == '3DVar'][column].mean():.4f}")

bias_gow: 0.0795
bias_cop: 0.1948
rmse_gow: 0.1508
rmse_cop: 0.2473
pearson_gow: 0.9859
pearson_cop: 0.9826
si_gow: 0.1190
si_cop: 0.2095